server:
  port: 8088

spring:
  application:
    name: freemarker-demo
  freemarker:
    cache: false #关闭模版缓存，方便测试
    settings:
      template_update_delay: 0 # 检查模版更新延迟时间，设置为0表示立即检查，如果大于0，会有缓存，不方便进行模版测试